nome: Customer Segmentation
versao: 1.0
descricao: |
  Perguntas de negócio que este pill procura responder?
  - Em quantas categorias os clientes podem ser segmentados?
  - Quais categorias sao mais interessantes para o meu empreendimento?

  Como a pill funciona?
 

  Nos campos abaixo, adicione os dados de entrada para treinar o modelo.
  Campos marcados com * sao obrigatórios.
links_referencias:
  Codex Aplicações de DS na DP6 - Forecasting: 'https://codex.dp6.io/books/ci%C3%AAncia-de-dados-bd4/page/forecasting'
  
parametros:
  dataset: 
    df:
      titulo: Tabela Passado
      descricao: Tabela com dados do passado para treinar o modelo
      obrigatorio: True
    regressores_futuros:
      titulo: Tabela Dados Adicionais
      descricao: Tabela com dados os dados adicionais (caso tenha adicionado) referentes ao período que deseja prever  
  input:
    config:
      blocos:
        bloco_1: 1. Data
        bloco_2: 2. Modelling
        bloco_3: 3. Posprocessing
      topicos: 
        bloco_1:
          topico_1: Dataset
        bloco_2:
          topico_1: Clusters
        bloco_3:
          topico_1: Importance Features
          topico_2: Custom Names
    widgets:
      bloco_1:
        topico_1:
          coluna_id:
            tipo: column
            titulo: Column ID
            descricao: Nome da coluna com os ID's dos clientes
            obrigatorio: True
          colunas_caracteristicas:
            tipo: columns
            titulo: Column Caracteristics
            descricao: Nomes das colunas que se referem a caracteristicas do cliente
            opcao: df
            obrigatorio: True
      bloco_2:
        topico_1:
          control_number_clusters:
            tipo: bool
            titulo: Add custom number
            descricao: Add custom number
          number_clusters:
            tipo: int
            titulo: Number of clusters
            descricao: Number of clusters
            controle: control_number_clusters
      bloco_3:
        topico_1:
          control_importance_features:
            tipo: bool
            titulo: Add importance features
            descricao: Add importance features
            posprocesso: True
          importance_features:
            tipo: columns
            titulo: Colunas
            descricao: Nomes das colunas para analise de importancia
            opcao: df
            controle: control_importance_features
            posprocesso: True
        topico_2:
          control_custom_features:
            tipo: bool
            titulo: Add custom names to clusters
            descricao: Add custom names to clusters
            posprocesso: True
    
    
  outputs_model:
    clustering_raw:
      tipo: DataFrame
      descricao: Segmentacao dos clientes pelos clusters
    clusters_statistics_raw:
      tipo: DataFrame
      descricao: Dados estatisticos dos clusters
    plot_optimal_clusters_k:
      tipo: fig
      descricao: Otimizacao do numero de Clusters K - Grafico Elbow Method
    plot_clusters_features_heatmap_raw:
      tipo: fig
      descricao: Relacao entre Clusters e Features - Grafico Heatmap
    plot_clusters_features_scatter_raw:
      tipo: plotly
      descricao: Relacao entre Clusters e Features - Grafico Matrix Scatter Plot
    dropped_ids_raw:
      tipo: DataFrame
      descricao: ID's retirados da base 

  outputs_posprocessing:
    model_hierarchy_raw:
      tipo: DataFrame
      descricao: Segmentacao dos clientes pelos clusters
    model_hierarchy_statistics_raw:
      tipo: DataFrame
      descricao: Dados estatisticos dos clusters
    plot_model_hierarchy_features_heatmap:
      tipo: fig
      descricao: Relacao entre Clusters e Features - Grafico Heatmap
    plot_model_hierarchy_features_scatter:
      tipo: plotly
      descricao: Relacao entre Clusters e Features - Grafico Matrix Scatter Plot
    

tests:
  dataframe:
    df: "RFV.csv"
  inputs:
    coluna_id: id
    colunas_caracteristicas: valor,frequencia,resc
    
    
  
